### ISSUE TITLE
Performing upgrade/update failing with missing rhvm package when product is RHV

### ISSUE THREAD

**Issue by petr-balogh** [oVirt/ovirt-ansible-engine-setup#33]
This task is problematic and failing when performing update/upgrade cause once rhvm is installed it's locked by yum versionlock plugin and looks like unavailable. So installing of this package  in task below:
```yaml
- name: Install RHV package
  package:
    name: "{{ 'rhevm' if ovirt_engine_setup_version is version('4.2', '<') else 'rhvm' }}"
    state: present
  when: ovirt_engine_setup_product_type | lower == 'rhv'
```

Failing with:
`2018-11-29 17:17:36,417 p=58857 u=root |  fatal: [jenkins-vm-03.lab.eng.tlv2.redhat.com]: FAILED! => {"changed": false, "msg": "No package matching 'rhvm' found available, installed or updated", "rc": 126, "results": ["No package matching 'rhvm' found available, installed or updated"]}`
